### ISSUE TITLE
add formatic

### ISSUE THREAD

**Issue by noxonsu** [Nasirdin/metamask#1]
нужно сделать логин по телефону

**Comment by noxonsu** [comment]
![](https://screenshots.wpmix.net/chrome_XbpnWTYbVnxlQYEhO1dzaYLAYwYcPEcH.png)

**Comment by Nasirdin** [comment]
https://user-images.githubusercontent.com/65252165/152221668-729a8b0a-fe25-49b7-be43-6cc55e73a7d0.mp4

**Comment by Nasirdin** [comment]
Готово

**Comment by Disti4ct** [comment]
> video.mp4

Formatic тормозит. Пока со своим телефоном не могу подключиться, может из-за тестнета.

Текст в кнопке не обновляется, если закрывать окно )

![pog123](https://user-images.githubusercontent.com/61930014/152506037-1736b293-53e7-4922-ad6b-a7c796856251.png)
![o1g2](https://user-images.githubusercontent.com/61930014/152506046-2805ba57-7bac-429b-95d1-a966122808db.png)

**Comment by Nasirdin** [comment]
Готово
